from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views
urlpatterns = [
    path('', views.apiOverView, name="api-overview"),
    path('users', views.userList, name="All Avilable Users"),
    path('suser/<str:pk>', views.userSearch, name="search specific user"),
    path('addcourses',
         views.addCourse, name="Add New Course"),
    path('getcookie', views.getCsrfCookie.as_view()),
    path('viewcourses', views.viewCourses, name="View All Courses"),
    path('addsubject', views.addSubject, name="Add Subject"),
    path('viewsubject', views.viewSubject, name="View SUbject"),
    path('viewsubject/<str:pk>', views.getSubject,
         name="get subject by staff id"),
    path('viewsubjectbysid/<str:pk',
         views.viewSubjectById, name="view subject by id"),
    path('usesid/<str:pk>', views.useSearchi, name="usersearch id"),
    path('coursen/<str:pk>', views.getCourseName, name="get couse name"),
    path('addsessionyear', views.addSessionYear, name="add session year"),
    path('addresult', views.addresult, name="add result"),
    path('getresult/<str:pk>', views.getresult, name="get result"),
    path('getresults/<str:pk>', views.getresultByStudent, name="get result"),
    path('editresult/<str:pk>', views.editresult, name="edit result"),
    path('editstaffleave/<str:pk>', views.editstaffleave, name="edit staff leave"),
    path('editstudentleave/<str:pk>',
         views.editstudentleave, name="edit student leave"),
    path('editattendance/<str:pk>', views.editattendance, name="edit attendance"),
    path('editstafffeedback/<str:pk>',
         views.editstafffeedback, name="edit staff feedback"),
    path('editstudentfeedback/<str:pk>',
         views.editstudentfeedback, name="edit staff feedback"),
    path('viewsessionyear', views.viewSessionYear, name="view session year"),
    path('addstudentfeedback', views.addStudentFeedBack,
         name="add student feedback"),
    path('getstudentfeedback', views.getStudentFeedBack, name="getstudentfeedback"),
    path('addstafffeedback', views.addStaffFeedBack,
         name="add staff feedback"),
    path('getstafffeedback', views.getStaffFeedBack, name="getstafffeedback"),
    path('getstafffeedback/<str:pk>',
         views.getStaffFeedBackById, name="getstafffeedback"),
    path('getstudentfeedback/<str:pk>',
         views.getstudentfeedBackByID, name="getstudentfeedback"),
    path('getstudentleave', views.getStudentLeave, name="Get Student Leave"),
    path('getstudentleave/<str:pk>',
         views.getstudentleaveById, name="Get Student Leave"),
    path('addstudentleave', views.addStudentLeave, name="Add Student Leave"),
    path('getstaffleave', views.getStaffLeave, name="Get Staff Leave"),
    path('getstaffleave/<str:pk>', views.getStaffLeavebyid,
         name="Get Staff Leave By Id "),
    path('addstaffleave', views.addStaffLeave, name="Add Staff Leave"),
    path('getattendance', views.getatendance, name="Get Atendance"),
    path('getattendancebi/<str:pk>', views.getatendanceById, name="Get Atendance"),
    path('addattendance', views.addatendance, name="Add Atendance"),
    path('getattendancereport/<str:pkss>', views.getattendancereport,
         name="Get Atendance Report"),
    path('getattendancereportbi/<str:pkss>', views.getattendancereportById,
         name="Get Atendance Report"),
    path('addattendancereport', views.addattendancereport,
         name="Add Atendance Report "),
    path('getattendancedate/<str:sid>/<str:ssid>',
         views.getattendancedate, name="get attendance date"),
    path('sendstaffnotification', views.sendstafffnotification,
         name="Send Staff Notification"),
    path('getstaffnotification/<str:pk>', views.getstaffnotification,
         name="Get staff Notification"),
    path('getstudentnotification/<str:pk>',
         views.getstudentnotification, name="Get Student Notification"),
    path('sendstudentnotification', views.sendstudentnotification,
         name="Send Student Notification"),
    path('enrollstudent', views.addenroledstudent, name="Enroll Student"),
    path('edituser/<str:pk>', views.edituser, name="Edit user"),
    path('editcourse/<str:pk>', views.editcourse, name="Edit Course"),
    path('editsub/<str:pk>', views.editsub, name="Edit subject"),
    path('deletesub/<str:pk>', views.deletesubject, name="Delete subject"),
    path('deletecur/<str:pk>', views.deletecourses, name="Delete Course"),
    path('deleteuser/<str:pk>', views.deletestudent, name="Delete User"),
    path('getenroled', views.getenroledstudent, name="Get Enroled Student"),
    path('getsbyc/<str:pk>', views.getsbycid, name="N/A")

]
