# Generated by Django 3.0.5 on 2021-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='types',
            field=models.IntegerField(default=1),
        ),
    ]
