# Generated by Django 3.0.5 on 2021-05-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210514_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='types',
            new_name='user_types',
        ),
    ]
